spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt_practice
    username: root
    password: thapelo123
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: GrTVUn9CZkcdCnNXU77nVvgzVfFHw5EXJ3Rnepxnx3P0cL8LmOOCYj7eVuocdOk